# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 05:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievements',
            name='importance',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cocurricular',
            name='importance',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='advisor',
            field=models.CharField(default='Dr. Manish Shrivastava', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='types',
            field=models.CharField(blank=True, choices=[('Misc', 'Misc'), ('Research', 'Research'), ('Developer', 'Developer')], default='Developer', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='work_experience',
            name='importance',
            field=models.CharField(default=5, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profiles',
            name='types',
            field=models.CharField(blank=True, choices=[('Misc', 'Misc'), ('Research', 'Research'), ('Developer', 'Developer')], default='Developer', max_length=10, null=True),
        ),
    ]
