# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0004_auto_20170426_0624'),
    ]

    operations = [
        migrations.AddField(
            model_name='publications',
            name='importance',
            field=models.IntegerField(default=5),
        ),
    ]
