# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0005_publications_importance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='end_date',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='projects',
            name='start_date',
            field=models.CharField(max_length=20),
        ),
    ]
