# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0006_auto_20170426_0648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='types',
            field=models.CharField(blank=True, choices=[('Misc', 'Misc'), ('Research', 'Research'), ('Developer', 'Developer')], default='Developer', max_length=20, null=True),
        ),
    ]
