# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0007_auto_20170426_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='advisor',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='projects',
            name='end_date',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='projects',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='projects',
            name='start_date',
            field=models.CharField(max_length=40),
        ),
    ]
