# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0009_projects_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiles',
            name='name',
        ),
        migrations.AlterField(
            model_name='profiles',
            name='profile_name',
            field=models.CharField(max_length=100),
        ),
    ]
