# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0010_auto_20170426_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='advisor',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
