# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0012_projects_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileinfo',
            name='github_nick',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
