# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0013_profileinfo_github_nick'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='year_started',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
