# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0014_auto_20170426_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='year_ended',
            field=models.CharField(max_length=20),
        ),
    ]
