# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0015_auto_20170426_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='work_experience',
            name='end',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='work_experience',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='work_experience',
            name='start',
            field=models.CharField(max_length=20),
        ),
    ]
