# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0016_auto_20170426_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work_experience',
            name='link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
